package ccm.admin.journey.repository;

import ccm.admin.journey.entity.Journey;
import ccm.admin.journey.entity.enums.JourneyStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;

@Repository
/**
 * repository - Repository Interface - Data access for Journey entities
 */

public interface JourneyRepository extends JpaRepository<Journey, Long>, JpaSpecificationExecutor<Journey> {

    /**
     * Count journeys by status
     */
    long countByStatus(JourneyStatus status);

    /**
     * Calculate total credits generated from verified journeys
     */
    @Query("SELECT COALESCE(SUM(j.creditsGenerated), 0) FROM Journey j WHERE j.status = 'VERIFIED'")
    BigDecimal calculateTotalCreditsGenerated();

    /**
     * Get total count for statistics
     */
    @Query("SELECT COUNT(j) FROM Journey j")
    long getTotalCount();

    /**
     * Count journeys created by a specific user
     *
     * @param userId The user ID
     * @return Number of journeys
     */
    @Query("SELECT COUNT(j) FROM Journey j WHERE j.userId = :userId")
    long countByUserId(@Param("userId") Long userId);

    /**
     * Sum total credits generated by a specific user (VERIFIED journeys only)
     *
     * @param userId The user ID
     * @return Total credits generated
     */
    @Query("SELECT COALESCE(SUM(j.creditsGenerated), 0) FROM Journey j WHERE j.userId = :userId AND j.status = 'VERIFIED'")
    BigDecimal sumCreditsByUserId(@Param("userId") Long userId);
}
