"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { mockReports, mockUsers } from "@/lib/mock-data"
import { Download } from "lucide-react"
import { useToast } from "@/hooks/use-toast"

export function ReportHistory() {
  const { toast } = useToast()

  const handleDownload = (reportId: string) => {
    toast({
      title: "Download Started",
      description: "Your report is being downloaded.",
    })
  }

  const getReportTypeColor = (type: string) => {
    switch (type) {
      case "users":
        return "bg-blue-100 text-blue-900 dark:bg-blue-900 dark:text-blue-100"
      case "transactions":
        return "bg-emerald-100 text-emerald-900 dark:bg-emerald-900 dark:text-emerald-100"
      case "credits":
        return "bg-purple-100 text-purple-900 dark:bg-purple-900 dark:text-purple-100"
      case "revenue":
        return "bg-amber-100 text-amber-900 dark:bg-amber-900 dark:text-amber-100"
      default:
        return ""
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Generated Reports</CardTitle>
        <CardDescription>View and download previously generated reports</CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Type</TableHead>
              <TableHead>Date Range</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Generated At</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {mockReports.map((report) => {
              const generator = mockUsers.find((u) => u.id === report.generatedBy)
              return (
                <TableRow key={report.id}>
                  <TableCell>
                    <Badge className={getReportTypeColor(report.type)}>{report.type}</Badge>
                  </TableCell>
                  <TableCell>
                    {new Date(report.dateRange.start).toLocaleDateString()} -{" "}
                    {new Date(report.dateRange.end).toLocaleDateString()}
                  </TableCell>
                  <TableCell>{generator?.name}</TableCell>
                  <TableCell>{new Date(report.generatedAt).toLocaleDateString()}</TableCell>
                  <TableCell>
                    <Badge variant="outline">{report.format.toUpperCase()}</Badge>
                  </TableCell>
                  <TableCell>
                    <Button size="sm" variant="outline" onClick={() => handleDownload(report.id)}>
                      <Download className="h-4 w-4 mr-1" />
                      Download
                    </Button>
                  </TableCell>
                </TableRow>
              )
            })}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  )
}
