CREATE TABLE IF NOT EXISTS verification_requests (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    distance DOUBLE PRECISION,
    energy_used DOUBLE PRECISION,
    co2_reduced DOUBLE PRECISION,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    remark TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
