package ccm.admin.journey.repository;

import ccm.admin.journey.entity.Journey;
import ccm.admin.journey.entity.enums.JourneyStatus;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
/**
 * repository - Repository Interface - Data access for Journey entities
 */
public interface JourneyRepository extends JpaRepository<Journey, Long>, JpaSpecificationExecutor<Journey> {

    /** Count journeys by status */
    long countByStatus(JourneyStatus status);

    /** Calculate total credits generated from verified journeys */
    @Query("SELECT COALESCE(SUM(j.creditsGenerated), 0) FROM Journey j WHERE j.status = 'VERIFIED'")
    BigDecimal calculateTotalCreditsGenerated();

    /** Get total count for statistics */
    @Query("SELECT COUNT(j) FROM Journey j")
    long getTotalCount();

    /** Count journeys created by a specific user */
    @Query("SELECT COUNT(j) FROM Journey j WHERE j.userId = :userId")
    long countByUserId(@Param("userId") Long userId);

    /** Sum total credits generated by a specific user (VERIFIED journeys only) */
    @Query("SELECT COALESCE(SUM(j.creditsGenerated), 0) FROM Journey j WHERE j.userId = :userId AND j.status = 'VERIFIED'")
    BigDecimal sumCreditsByUserId(@Param("userId") Long userId);

    /** Retrieve journeys by status for CVA workflows */
    Page<Journey> findByStatus(JourneyStatus status, Pageable pageable);

    /** Journeys created within window for analytics */
    java.util.List<Journey> findAllByCreatedAtBetweenOrderByCreatedAtAsc(LocalDateTime from, LocalDateTime to);

    /** Journeys verified within window for analytics */
    java.util.List<Journey> findAllByVerifiedAtBetweenOrderByVerifiedAtAsc(LocalDateTime from, LocalDateTime to);
}
