"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { RefreshCw, Info } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import { useReportApi, ReportHistory as ReportHistoryType } from "@/lib/hooks/useAdminApi"
import { Skeleton } from "@/components/ui/skeleton"
import { Alert, AlertDescription } from "@/components/ui/alert"

export function ReportHistory() {
  const [reports, setReports] = useState<ReportHistoryType[]>([])
  const { getReportHistory, loading, error } = useReportApi()
  const { toast } = useToast()

  useEffect(() => {
    loadReportHistory()
  }, [])

  const loadReportHistory = async () => {
    const result = await getReportHistory({ page: 0, size: 50 })
    if (result) {
      setReports(result.content || [])
    }
  }

  const getReportTypeColor = (type: string) => {
    const normalized = type.toLowerCase()
    switch (normalized) {
      case "users":
      case "user":
        return "bg-blue-100 text-blue-900 dark:bg-blue-900/30 dark:text-blue-400"
      case "transactions":
      case "transaction":
        return "bg-emerald-100 text-emerald-900 dark:bg-emerald-900/30 dark:text-emerald-400"
      case "credits":
      case "carbon_credits":
        return "bg-purple-100 text-purple-900 dark:bg-purple-900/30 dark:text-purple-400"
      case "revenue":
        return "bg-amber-100 text-amber-900 dark:bg-amber-900/30 dark:text-amber-400"
      default:
        return "bg-gray-100 text-gray-900 dark:bg-gray-900/30 dark:text-gray-400"
    }
  }

  const formatDateTime = (dateString: string) => {
    return new Date(dateString).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  if (loading && reports.length === 0) {
    return (
      <Card>
        <CardHeader>
          <Skeleton className="h-6 w-40" />
          <Skeleton className="h-4 w-64 mt-2" />
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Generated Reports</CardTitle>
            <CardDescription>View history of previously generated reports</CardDescription>
          </div>
          <Button variant="outline" size="sm" onClick={loadReportHistory} disabled={loading}>
            <RefreshCw className={`h-4 w-4 mr-2 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <Alert>
          <Info className="h-4 w-4" />
          <AlertDescription>
            Reports are generated on-demand and not stored. Use the "Generate Report" tab to create new exports.
          </AlertDescription>
        </Alert>

        {error && (
          <Alert variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {reports.length === 0 ? (
          <div className="text-center py-12 text-muted-foreground">
            <p>No reports have been generated yet</p>
          </div>
        ) : (
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Type</TableHead>
                  <TableHead>Date Range</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Generated At</TableHead>
                  <TableHead>Format</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>
                      <Badge className={getReportTypeColor(report.type)} variant="secondary">
                        {report.type}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm">{report.dateRange || "All dates"}</TableCell>
                    <TableCell>
                      <div>
                        <p className="font-medium text-sm">{report.generatedByName}</p>
                        <p className="text-xs text-muted-foreground">{report.generatedByEmail}</p>
                      </div>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {formatDateTime(report.generatedAt)}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="uppercase">
                        {report.format}
                      </Badge>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
